version: 0.2.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore source\AutoReviser.sln
build:
  verbosity: minimal
after_build:
test:
  assemblies: '**\*.tests.dll'
artifacts:
- path: '**\AutoReviser.**.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: lsntLeh0+0gJFZSpHd88aml765YgNzvYWQo+uQVm4LFw3fhOk5F874QdqyvvPCZw
  artifact: /.*\.nupkg/
