version: 0.2.{build}
image: Visual Studio 2022
configuration: Release
before_build:
- cmd: nuget restore source\AutoReviser.sln
build:
  verbosity: minimal
after_build: []
artifacts:
- path: '**\AutoReviser.**.nupkg'
- path: '**\AutoReviser.**.snupkg'
deploy:
- provider: NuGet
  server:
  api_key:
    secure: Uzn2AXvXAtrab/enLy+Qm0N2rlqODwmTOUu9hUMzYDvOlsFkbwEbgdG9srtBqTKH
  skip_symbols: false
  symbol_server:
